spring:
  config:
    import: optional:classpath:.env
  application:
    name: InitiativeNouvelleAquitaine
  datasource:
    url: jdbc:postgresql://localhost:5432/InitiativeProjet
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
flyway:
  url: jdbc:postgresql://localhost:5432/InitiativeProjet
  username: postgres
  password: postgres
  enabled: true
  locations: classpath:db/migration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
jwt:
  secret: B#MaYYnJCwe5|?=G
  expiration: 3600